on:
    release:
        types: [created]

jobs:
    release:
        name: release (${{ matrix.flavor }}, ${{ matrix.os }})
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                flavor: [minimal, gui]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@master
            - name: Install GTK
              if: matrix.flavor == 'gui' && matrix.os == 'ubuntu-latest'
              run: sudo apt install libgtk-3-dev
            - name: Compile and release
              uses: taiki-e/upload-rust-binary-action@v1
              with:
                  bin: dsc-merger
                  token: ${{ secrets.RELEASE_TOKEN }}
                  features: ${{ matrix.flavor == 'gui' && 'gui' || '' }}
                  checksum: sha256
                  include: LICENSE,README.md
                  archive: $bin-$tag-$target-${{ matrix.flavor }}
