on:
    release:
        types: [created]

jobs:
    release:
        name: release ${{ matrix.target }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: ubuntu-latest
                      flavor: ["minimal", "gui"]
                    - os: windows-latest
                      flavor: ["minimal", "gui"]
                    - os: macos-latest
                      flavor: ["minimal", "gui"]
        steps:
            - uses: actions/checkout@master
            - name: Compile and release
              uses: taiki-e/upload-rust-binary-action@v1
              with:
                  bin: dsc-merger
                  token: ${{ secrets.RELEASE_TOKEN }}
                  features: ${{ matrix.flavor == 'gui' && 'gui' || '' }}
                  checksum: sha256
                  include: LICENSE,README.md
                  archive: $bin-$tag-$target-${{ matrix.flavor }}
